### ISSUE TITLE
Feature Request: protected labels

### ISSUE THREAD

**Issue by lemeurherve** [timja/github-comment-ops#33]
### What feature do you want to see added?

I'd like to be able to restrict addition/removal of certain labels to people with enough permissions on the repository.

**Comment by timja** [comment]
Can you give an example of which labels and why?

**Comment by lemeurherve** [comment]
I intend to automate status notices with issues labels on jenkins-infra/helpdesk, and might need to be able to limit certain labels.
I'm also thinking about security reviews and associated labels currently discussed elsewhere.

Nothing done, this FR may be premature.

**Comment by lemeurherve** [comment]
> I intend to automate status notices with issues labels on jenkins-infra/helpdesk, and might need to be able to limit certain labels.

Thinking about it, I could also add a specific command for this 🤔 

I didn't posted this another FR but if other commands are added it could be nice to be able to disable some of them depending on the org. (Not sure how it could be done as currently this works without any notion of org AFAIU)

**Comment by timja** [comment]
For a status page I would probably just have an issue template for it. 

So you get all the fields, dates etc.
and the label will get automatically added on issue open

**Comment by lemeurherve** [comment]
That's what I've planned, we"re on the same page.
I was thinking about publishing the notice on specific label addition, but I like the github comment ops way far more! It was in my personal backlog, your tool is a timely opportunity :)
