### ISSUE TITLE
multiple reviewers should be space separation.

### ISSUE THREAD

**Issue by jetersen** [timja/github-comment-ops#35]
https://github.com/timja/github-comment-ops/blob/26bc7b96705a06c1003ccbd12ac4220af2891ea4/index.js#L121

@timja this should potentially handle spaces instead of comma separation.

One they cannot have spaces in their username.
Two by default the auto complete fills in a space when hitting enter for completion.

`@timja @jetersen @etc`

**Comment by lemeurherve** [comment]
I'd still keep the comma to be coherent with the `/label` command with a comma separator accepting labels with spaces

**Comment by jetersen** [comment]
I'd suggest writing some tests 😉

https://github.com/updatecli/updatecli-action/pull/100

**Comment by timja** [comment]
> Should be relatively easy
> 
> Believe you can do
> 
> ```js
> const reviewersToBeParsed = reviewerMatches[1].split("[, ]");
> ```

The tests failed with this, I just did:

```javascript
  const separator = reviewers.includes(",") ? "," : " ";
  const split = reviewers.split(separator);
```

**Comment by jetersen** [comment]
@timja 

The correct syntax is `/regex/` by bad :D

```
const split = reviewers.split(/[,\s]/);
```

**Comment by timja** [comment]
sure not sure if I really want to support both at the same time anyway, so my approach should be fine?

**Comment by jetersen** [comment]
Why not regex can handle splitting correctly for both? 😅

**Comment by timja** [comment]
yeah sure have merged
