### ISSUE TITLE
PR is not labeled on jenkinsci repository

### ISSUE THREAD

**Issue by NotMyFault** [timja/github-comment-ops#53]
I tried to use the bot on https://github.com/jenkinsci/maven-plugin/pull/281, but the label is not added, though the label exists https://github.com/jenkinsci/maven-plugin/labels/bug.

**Comment by timja** [comment]
Looks like @daniel-beck suspended it.

I have unsuspended it as he has not gone through the proper process.

@daniel-beck please raise a helpdesk issue and start a discussion there.

The bot went through the INFRA helpdesk, it was discussed there by a number of contributors, it was discussed at the UX sig meeting, and has been announced on the jenkinsci-dev mailing list

**Comment by daniel-beck** [comment]
> has been announced on the jenkinsci-dev mailing list

Where? I checked and didn't find it.

**Comment by timja** [comment]
After a proper discussion at Daniel's request I've temporarily limited the repositories in the jenkinsci org to:

- jenkins
- design-library-plugin
- jenkins-infra-test-plugin
This is to gather feedback and in a couple of weeks if there's no objections we can enable globally.

There is a jenkinsci developer thread at: https://groups.google.com/g/jenkinsci-dev/c/sE7mH7hUZSY
